name: Hello World Valcann

on:
  push:
    branches:
      - main
      
      
jobs: 
  echo-hello-world: 
    runs-on: ubuntu-latest
    steps:
      - name: Printar Hello World
        run: echo hello world
      
